### ISSUE TITLE
"Address already in use" error while running on a remote server

### ISSUE THREAD

**Issue by daanishmahajan** [LooseLab/Icarust#14]
Hi @Adoni5, 
I am getting the following error (image attached) while running on the remote server (having CentOS 8.3):

**Command Run:** 
`cargo run --release -- -s Profile_tomls/test.toml -v`

**Error:** 

`tonic::transport::Error(Transport, hyper::Error(Listen, Os { code: 98, kind: AddrInUse, message: "Address already in use" }))`

When I run the same on my local MacOS, it works fine.

<img width="1512" alt="Screenshot 2024-05-07 at 22 13 10" src="https://github.com/LooseLab/Icarust/assets/28214507/3244de36-f8ff-442d-8d0c-6923b5769d1e">

**Comment by Adoni5** [comment]
HI @daanishmahajan, Thanks for giving Icarust a try!
I won't have time to look too deeply today, but is there a chance that some over service is listening on port 10000 or 10001?

If you try changing the ports in the `config.ini` file to something else. like 11000 and 11001, does that fix it?

Alternatively you can check if the port is in use with the following command:

```bash
netstat -tuln | grep LISTEN | grep -E '10000|10001'
```

It should list if a service is already listening on that port

Thanks,
Rory

**Comment by daanishmahajan** [comment]
Thanks, @Adoni5, changing the port worked!
