### ISSUE TITLE
Running Icarust on singularity issue (`could not read config.ini`) 

### ISSUE THREAD

**Issue by lborcard** [LooseLab/Icarust#19]
Dear Team,

I am trying to run icarust in a singularity image from the pulled docker image but I am encountering an issue with the config.ini files that is not found :

`singularity exec -B ./configs/:/configs -B ./squiggle_arrs/:/squiggle_arrs -B ./output/:/tmp --network-args "portmap=10000:10001/tcp" icarust_latest.sif icarust -s /configs/config_dnar10_barcoded.toml -vv`

`Error: "couldn't read config.ini: No such file or directory (os error 2)"`

I mount the config file properly and they are present in the image in `/configs/` 

best,

Loïc

**Comment by Adoni5** [comment]
Hi Loïc,

Can you try, passing `icarust -c /configs/config.ini -s /configs/config_dnar10_barcoded.toml -vv`?

**Comment by lborcard** [comment]
This is what I am getting 
``` 
[2024-06-20T15:45:05Z INFO icarust::impl_services::data: 307 ] Fetching barcode squiggle for barcode Barcode01 at static/barcode_squiggle/Barcode01_1_R10.squiggle.npy
thread 'main' panicked at src/impl_services/data.rs:288:77:
called `Result::unwrap()` on an `Err` value: Io(Os { code: 2, kind: NotFound, message: "No such file or directory" })
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by lborcard** [comment]
when I run  `ls /configs/config.ini` it can be found, I tried chmod the folder containing it but it did not help

**Comment by lborcard** [comment]
closing it since I can use the docker version

**Comment by Adoni5** [comment]
Hi @lborcard - please reopen this if you have any issues using the docker version!
