### ISSUE TITLE
`start_time` in fastq file not available afterbasecalling

### ISSUE THREAD

**Issue by lborcard** [LooseLab/Icarust#20]
Dear Icarust,

I am testing your software and I just noticed that the fastq files that I obtained from Dorado (HAC) do not contain the start_time in the fastq header. Is this info available somewhere after the run ? I ran Icarust from the docker using `-vvv` flag.

thank you!

Loïc

**Comment by Adoni5** [comment]
Hi @lborcard - sorry for the slow reply!
Is this still an issue? I _think_ the start time should be present, but it might not represent the actual read start time.

Cheers,
Rory

**Comment by lborcard** [comment]
Hi @Adoni5 ,

At least using my version of dorado, the resulting fastqs do not have the start_time flag in their headers. I tried to use readfish to circumvent that as it outputs the time of the "decision" but this timing seems to be off .
