### ISSUE TITLE
RuntimeError: Server response not formatted correctly: <result.bad_reply: 14>

### ISSUE THREAD

**Issue by lborcard** [LooseLab/Icarust#21]
Hi there,

I am running into this error running readfish (2023.1.1) with Icarust ( native). I have tried so many different config but I cannot run readfish with icarust.

best,

Loïc

**Comment by mattloose** [comment]
Which basecaller and version are you using? And does it match the version of the ont basecaller library installed?

**Comment by lborcard** [comment]
I am using dorado  (7.3.11) but readfish message mentioned it did not have any module called dorado after I changed the toml params. I tried to set it back to guppy but I received this error message.  Are there other parameters to setup to use live basecalling ?

**Comment by lborcard** [comment]
After verification I was running an older version of readfish, now I am getting an certificate error. Thank you for the help !

**Comment by lborcard** [comment]
I could finally identify the problem, it was related to readfish and dorado parameters that were not properly set. Thank you I am closing this.

**Comment by Adoni5** [comment]
brilliant, sorry for the slow reply!
Been very busy 😢
